import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import Providers from "./providers";
import localFont from "next/font/local";
import { Footer } from "@/components/Footer";
import QueryClientProviderComponent from "@/providers/QueryClientProviderComponent";

const ceraPro = localFont({
    src: [
        {
            path: "../fonts/CeraPro-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/CeraPro-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../fonts/CeraPro-Medium.woff2",
            weight: "500",
            style: "normal",
        },
    ],
    variable: "--font-cera-pro",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${ceraPro.variable} antialiased`}>
                <QueryClientProviderComponent>
                    <Providers>
                        <div>
                            <header>
                                <Header />
                            </header>

                            {children}
                            <footer>
                                <Footer />
                            </footer>
                        </div>
                    </Providers>
                </QueryClientProviderComponent>
            </body>
        </html>
    );
}
